# Generated by Django 2.1.3 on 2018-11-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglist', '0002_auto_20181105_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(max_length=50, verbose_name='Car Number')),
                ('location', models.CharField(blank=True, max_length=10)),
                ('parking_time', models.DateTimeField(verbose_name='time in')),
                ('exit_time', models.DateTimeField(blank=True, verbose_name='time out')),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('current_exist', models.BooleanField(default=0, verbose_name='In lot')),
            ],
        ),
        migrations.DeleteModel(
            name='Parkinglot',
        ),
    ]
