# Generated by Django 2.1.3 on 2018-11-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglist', '0003_auto_20181109_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time out'),
        ),
    ]
