# Generated by Django 2.1.3 on 2018-11-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglist', '0005_auto_20181127_1925'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
