# Generated by Django 2.1.3 on 2018-11-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglist', '0006_auto_20181127_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='currparkinglot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={},
        ),
    ]
