# [START django_app]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT djangoproject.wsgi

beta_settings:
  cloud_sql_instances: parkingsystem-221809:asia-east1:software7

runtime_config:
  python_version: 3

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: djangoproject.wsgi.application
# [END django_app]

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUD_SQL_CONNECTION_NAME: 'parkingsystem-221809:asia-east1:software7'
  CLOUD_SQL_USER_NAME: 'root'
  CLOUD_SQL_PASSWORD: '2018'
  CLOUD_SQL_DATABASE_NAME: 'project7'
  CHECK_INSTANCE: 'GAE'

  STATIC_URL: 'https://storage.googleapis.com/parkingsystem_static/static/'
